name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    schedule:
      - cron: 0 */4 * * *
  workflow_dispatch: # 支持手动触发

# 设置 GITHUB_TOKEN 的权限，允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 同一时间只允许一个部署，但不取消正在进行的部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # 根据你项目实际使用的 Go 版本修改
          cache: true # 自动缓存 Go 模块
      - name: Install mercury
        run: go install github.com/kgaughan/mercury/cmd/mercury@latest

      - name: Cache site generator cache
        uses: actions/cache@v4
        with:
          path: ./planet/cache  # 对应 --cache-dir 的路径
          key: site-cache-${{ hashFiles('planet/cache/**') }}
          restore-keys: |
            site-cache-

      - name: Generate static site
        run: |
          cd planet
          mercury

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./planet/output" # 改为你的生成器实际输出目录

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
